version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.09.0-ce

    steps:
      - setup_remote_docker:
          version: 17.09.0-ce
          docker_layer_caching: true

      - checkout

      - run:
          name: Build container
          command: |
            export CIRCLE_SHORT_SHA1=$(echo $CIRCLE_SHA1 | cut -c -7)
            ls -la
            docker build -t circleci-aiodocker:$CIRCLE_SHORT_SHA1 .

      - run:
          name: Run container
          command: |
            export CIRCLE_SHORT_SHA1=$(echo $CIRCLE_SHA1 | cut -c -7)
            DOCKER_ENV_FILE=$(mktemp)
            docker run --rm --env-file $DOCKER_ENV_FILE \
                circleci-aiodocker:$CIRCLE_SHORT_SHA1 pytest -s -vv tests

